export const appDescriptions: Record<string, string> = {
  "1password": "Keep passwords and secure information in one place.",
  "adobe-after-effects": "Create motion graphics and visual effects.",
  "adobe-illustrator": "Draw vector illustrations, icons, and graphics.",
  "adobe-indesign": "Lay out books, magazines, and digital publications.",
  "adobe-lightroom": "Organize and edit your photography.",
  "adobe-photoshop": "Edit images and create digital artwork.",
  "adobe-xd": "Design and prototype app and web interfaces.",
  "affinity-photo": "Retouch photos and compose layered images.",
  "android-studio": "Build and debug Android apps.",
  "apple-calendar": "Plan events and keep track of your schedule.",
  "apple-finder": "Browse files and organize your Mac.",
  "apple-notes": "Capture ideas, checklists, and everyday notes.",
  atom: "Write and edit code in a customizable editor.",
  claude: "Think, write, and work through ideas with AI.",
  discord: "Chat, share, and hang out with your communities.",
  fastmail: "Manage email, calendars, and contacts.",
  figjam: "Brainstorm and map ideas on a shared whiteboard.",
  figma: "Design interfaces and collaborate with your team.",
  firefox: "Browse the web with a focus on privacy.",
  framer: "Design and publish websites visually.",
  freeform: "Sketch ideas on an open canvas.",
  "github-desktop": "Manage Git repositories with a visual workflow.",
  gmail: "Read, organize, and send email.",
  "google-calendar": "Schedule events and coordinate your time.",
  "google-chrome": "Explore the web and manage your tabs.",
  "helix-editor": "Edit code directly from your terminal.",
  "ia-writer": "Focus on writing with a minimal Markdown editor.",
  "intellij-idea-eap": "Try upcoming IntelliJ IDEA features before release.",
  "intellij-idea": "Write, refactor, and debug Java and Kotlin.",
  iterm2: "Work with shells, tabs, and terminal sessions.",
  kitty: "Run your terminal with flexible tabs and layouts.",
  linear: "Plan projects and track your team's issues.",
  macos: "Navigate your Mac and manage windows and apps.",
  "microsoft-outlook": "Handle email, calendars, and contacts.",
  "microsoft-teams": "Bring team chats, meetings, and files together.",
  mindnode: "Turn thoughts into visual mind maps.",
  miro: "Collaborate on diagrams, plans, and shared boards.",
  notion: "Organize notes, documents, and projects.",
  numbers: "Create spreadsheets and make sense of your data.",
  obsidian: "Connect your notes in a personal knowledge base.",
  omnifocus3: "Organize tasks and projects with Getting Things Done.",
  omnifocus4: "Plan projects and keep your next actions clear.",
  "pixelmator-pro": "Edit photos and create polished graphics.",
  postman: "Build, test, and explore APIs.",
  principle: "Prototype animated and interactive interfaces.",
  "proto-io": "Create interactive prototypes for apps and websites.",
  safari: "Browse the web with Apple's native browser.",
  signal: "Send private messages and make secure calls.",
  sip: "Pick colors and build palettes for your designs.",
  sketch: "Design interfaces, components, and interactive prototypes.",
  slack: "Keep team conversations and work in one place.",
  spark: "Organize your inbox and stay on top of email.",
  spline: "Create interactive 3D scenes in your browser.",
  spotify: "Listen to music, podcasts, and playlists.",
  "sqlpro-studio": "Query databases and browse your data.",
  "sublime-text-windows": "Edit text and code with a fast, focused editor.",
  telegram: "Chat, share files, and follow your communities.",
  things: "Keep tasks, projects, and plans neatly organized.",
  todoist: "Track tasks and plan what to do next.",
  transmit: "Transfer files and manage remote servers.",
  typora: "Write Markdown with a clean, live document view.",
  "visual-studio-code": "Write and debug code across your projects.",
  xcode: "Build and debug apps for Apple platforms.",
  "zendesk-support": "Manage support tickets and help your customers.",
  zeplin: "Hand off designs and keep implementation aligned.",
  zoom: "Meet, present, and collaborate over video.",
};
